#!/usr/bin/env python3

import os
import sys
from glob import glob
import subprocess

changes = {
  'deleted': [],
  'added': [],
  'modified': []
}

section = None
for arg in sys.argv[1:]:
  if arg.startswith('--'):
    section = arg[2:]
    assert section in changes, f'Unexpected file category "{section}"'
  else:
    changes[section].append(arg)

def run(cmd):
  print('$ ' + ' '.join(cmd))
  result = subprocess.run(cmd, stdout=subprocess.PIPE).stdout.decode('utf-8')
  print(result)
  return result

def to_notebook(path):
  return os.path.splitext(path)[0] + '.ipynb'

for change, files in changes.items():
  src = None
  if os.path.splitext(path)[1] == '.py' and os.path.isfile(path):
    with open(path, 'r', encoding='utf-8') as f:
      for line in range(20):
        if f.readline().replace(' ', '').startswith('#%%'):
          src = path
          break
  if src is None:
    continue

  if change in ['modified', 'added']:
    tgt = to_notebook(src)
    print(src, '=>', tgt)
    run(['jupytext', src, '--to', 'ipynb', '--set-kernel', '-', '--output', tgt])
    run(['git', 'add', tgt])
  elif change == 'deleted':
    if os.path.exists(path):
      print(src, '=>', 'None')
      run(['git', 'rm', path])
