name: Execute notebooks

on:
  workflow_dispatch: null
  schedule:
  - cron: '5 13,16 * * 1-5' # in UTC / Winter NLtime -1 Summer NLtime -2 / LCPS in Summer = 12
  - cron: '30 13 * * 1-5'   # RIVM Summer = 13
  
jobs:
  publish:
    strategy:
      max-parallel: 1 # because knack is dense and we would clash with their 10/sec update limit
      matrix:
        notebook:
        - LeeftijdsgroepenLandelijk
        - Regio
        - Dagoverzicht
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KNACK_API_KEY: ${{ secrets.KNACK_API_KEY }}
      KNACK_APP_ID: ${{ secrets.KNACK_APP_ID }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
    - name: Cancel Previous Runs
      uses: styfle/cancel-workflow-action@0.8.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      if: github.event_name == 'push'
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
      if: github.event_name != 'push'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Cache python dependencies and data downloads
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install python requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip3 install -r requirements.txt
        pip3 install nbformat --upgrade
        pip freeze
    - name: Run ${{ matrix.notebook }}
      id: notebook
      run: |
        date
        python3 -m ipykernel install --name python3 --user
        jupytext ${{ matrix.notebook }}.py --to ipynb --set-kernel - --output - | papermill --log-output - ${{ matrix.notebook }}.ipynb
      env:
        PYTHONUNBUFFERED: 'true'
        NOTEBOOK: ${{ matrix.notebook }}
    - name: store build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: artifacts

    - name: grab data files
      if: always()
      run: |
        # grab updated data files
        ./setup.py

        # remove obsolete conversions
        for nb in *.ipynb; do
          if [ ! -f "${nb%.ipynb}.py" ]; then
            git rm $nb
          fi
        done

        # merge notebooks
        cat LeeftijdsgroepenLandelijk.py Regio.py Dagoverzicht.py > run-all.py
        git add run-all.py
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: always()
      continue-on-error: true
      with:
        commit_message: save data history
        file_pattern: rivm lcps *.ipynb github nice cbs
        skip_dirty_check: false
