name: Execute notebook

on:
  push: null
  schedule:
  - cron: 0 0 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel other runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6" # match Colab
    - name: Install requirements
      run: pip3 install jupyterlab pandas numpy papermill
    - name: Run notebook
      run: papermill --progress-bar Corona_locator.ipynb /dev/null 
      env:
        PYTHONUNBUFFERED: true
    - uses: stefanzweifel/git-auto-commit-action@v4
      continue-on-error: true
      with:
        commit_message: Publish notebook results
        file_pattern: corona.csv
        skip_dirty_check: false

