name: Execute notebook

on:
  push: null
  schedule:
  - cron: 0 0 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Cancel other runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Cache python dependencies and data downloads
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: v1
      with:
        path: |
          ~/.cache/pip
          **/downloads
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install requirements
      run: pip3 install -r requirements.txt
    - name: Run notebook
      run: |
        # seed history
        #if [ ! -f downloads/COVID-19_aantallen_gemeente_per_dag-2021-01-13@14-15.csv ]; then
        #  mkdir -p downloads
        #  curl -L -o yesterday.zip https://file.io/tpEjRjClGWDv
        #  (cd downloads && unzip ../yesterday.zip)
        #fi
        python -m ipykernel install --name python3 --user
        jupytext LeeftijdsgroepenLandelijk.py --to ipynb --set-kernel - --output - | papermill --log-output - output.ipynb
        jupytext Regios.py --to ipynb --set-kernel - --output - | papermill --log-output - output.ipynb
      env:
        PYTHONUNBUFFERED: true
    - name: store build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: artifacts
