name: Execute notebook

on:
  push: null
  schedule:
  - cron: '0 */8 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Cancel other runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
      if: github.event_name == 'push'
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
      if: github.event_name != 'push'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Cache python dependencies and data downloads
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install python requirements
      run: |
        python -m pip install --upgrade pip setuptools wheel
        pip3 install -r requirements.txt
    - name: Run notebook
      run: |
        set -x
        notebooks=(
        LeeftijdsgroepenLandelijk
        RegioV2
        DagOverzicht
        )
        python -m ipykernel install --name python3 --user
        for nb in ${notebooks[@]}; do
          jupytext $nb.py --to ipynb --set-kernel - --output $nb.ipynb
          papermill --log-output $nb.ipynb /tmp/output.ipynb
          #jupyter nbconvert --to notebook --execute $nb.ipynb
        done

        # remove obsolete conversions
        for nb in *.ipynb; do
          if [ ! -f "${nb%.ipynb}.py" ]; then
            rm $nb
          fi
        done
      env:
        PYTHONUNBUFFERED: true
    - name: store build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: artifacts

    - uses: stefanzweifel/git-auto-commit-action@v4
      with:
        commit_message: Update converted notebooks, save RIVM history
        file_pattern: rivm/*.gz lcps/*.gz *.ipynb
        skip_dirty_check: false

