name: Execute notebook

on:
  push: null
  schedule:
  - cron: 0 0 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Cancel other runs
        uses: styfle/cancel-workflow-action@0.6.0
        with:
          access_token: ${{ github.token }}
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
    - name: Run notebook
      run: jupyter nbconvert --to notebook --execute --ExecutePreprocessor.kernel_name=python3 --output output.ipynb Corona_locator.ipynb
