name: Execute notebook

on:
  workflow_dispatch: null
  schedule:
  - cron: '0 9,11 * * *'
  - cron: '5 13,15-19,21 * * *'
  - cron: '16,20 14 * * *'
  - cron: '35 14-16 * * *'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      KNACK_API_KEY: ${{ secrets.KNACK_API_KEY }}
      KNACK_APP_ID: ${{ secrets.KNACK_APP_ID }}
      SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
    steps:
    - uses: actions/checkout@v2
      if: github.event_name == 'push'
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.head_ref }}
      if: github.event_name != 'push'
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Cache python dependencies and data downloads
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install python requirements
      run: |
        python3 -m pip install --upgrade pip setuptools wheel
        pip3 install -r requirements.txt
        pip3 install nbformat --upgrade
        pip freeze
    - name: Run notebooks
      run: |
        date
        python3 -m ipykernel install --name python3 --user
        notebooks=(
        LeeftijdsgroepenLandelijk
        RegioV2
        DagOverzicht
        )
        for nb in ${notebooks[@]}; do
          echo ======================= $nb ============================
          export NOTEBOOK=$nb
          jupytext $nb.py --to ipynb --set-kernel - --output - | papermill --log-output - $nb.ipynb
        done
      env:
        PYTHONUNBUFFERED: true
    - name: store build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: artifacts

    - name: grab data files
      if: always()
      run: |
        # grab updated data files
        ./setup.py

        # remove obsolete conversions
        for nb in *.ipynb; do
          if [ ! -f "${nb%.ipynb}.py" ]; then
            git rm $nb
          fi
        done
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: always()
      continue-on-error: true
      with:
        commit_message: save data history
        file_pattern: rivm lcps *.ipynb github nice
        skip_dirty_check: false
