name: Execute notebook

on:
  push: null
  schedule:
  - cron: '0 */2 * * *'

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Cancel other runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ secrets.GITHUB_TOKEN }}
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.9"
    - name: Cache python dependencies and data downloads
      id: cache
      uses: actions/cache@v2
      env:
        cache-name: v1
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-build-${{ env.cache-name }}
    - name: Install python requirements
      run: pip3 install -r requirements.txt
    - name: Run notebook
      run: |
        python -m ipykernel install --name python3 --user
        jupytext LeeftijdsgroepenLandelijk.py --to ipynb --set-kernel - --output - | papermill --log-output - /tmp/output.ipynb
        jupytext Regio.py --to ipynb --set-kernel - --output - | papermill --log-output - /tmp/output.ipynb
      env:
        PYTHONUNBUFFERED: true
    - name: store build artifacts
      uses: actions/upload-artifact@v2
      with:
        path: artifacts

    - name: Check for notebook changes
      uses: dorny/paths-filter@v2
      if: github.event_name != 'schedule'
      id: committed
      with:
        list-files: shell
        filters: |
          added:
            - added: '[A-Z]*.py'
          modified:
            - modified: '[A-Z]*.py'
          deleted:
            - deleted: '[A-Z]*.py'
    - name: convert notebooks
      if: github.event_name != 'schedule'
      id: notebooks
      run: ./util/convert-notebooks --added ${{ steps.committed.outputs.added_files }} --modified ${{ steps.committed.outputs.modified_files }} --deleted ${{ steps.committed.outputs.deleted_files }}
    - uses: stefanzweifel/git-auto-commit-action@v4
      if: github.event_name != 'schedule'
      with:
        commit_message: Update converted notebooks, save RIVM history
        file_pattern: rivm/*.gz *.ipynb
        skip_dirty_check: false

