name: Execute notebook

on:
  push: null
  schedule:
  - cron: 0 0 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Cancel other runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6" # match Colab
    - name: Install requirements
      run: pip3 install jupyterlab pandas numpy papermill github3.py
    - name: Run notebook
      run: papermill --log-output Corona_locator.ipynb output.ipynb
      env:
        PYTHONUNBUFFERED: true
