name: Execute notebook

on:
  push: null
  schedule:
  - cron: 0 0 * * *

jobs:
  run:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
    - name: Cancel other runs
      uses: styfle/cancel-workflow-action@0.6.0
      with:
        access_token: ${{ github.token }}
    - uses: actions/checkout@v1
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: "3.6" # match Colab
    - name: Install requirements
      run: pip3 install jupyterlab pandas numpy papermill github3.py
    - name: Run notebook
      run: papermill --log-output Corona_locator.ipynb output.ipynb
      env:
        PYTHONUNBUFFERED: true
    - name: Make place for latest csv
      run: githubrelease asset ${{ github.repository }} delete covid covid.csv
      continue-on-error: true
    - name: Upload latest csv
      run: githubrelease asset ${{ github.repository }} upload covid covid.csv
    - name: Get current date
      id: date
      run: echo "name=$(date +'%Y-%m-%d')" >> $GITHUB_ENV
    - name: Make place for dated csv
      run: githubrelease asset ${{ github.repository }} delete covid ${{ steps.date.output.date }}.csv
      continue-on-error: true
    - name: Upload dated csv
      run: |
        mv covid.csv ${{ steps.date.output.date }}.csv
        githubrelease asset ${{ github.repository }} upload covid ${{ steps.date.output.date }}.csv
